BEGIN TRANSACTION;
DROP TABLE IF EXISTS "QUIZ_PROCESS";
CREATE TABLE IF NOT EXISTS "QUIZ_PROCESS" (
	"_id"	INTEGER PRIMARY KEY AUTOINCREMENT,
	"quiz_id"	INTEGER,
	"deckset_name"	TEXT,
	"section_name"	TEXT,
	"class_name"	TEXT,
	"term_id"	INTEGER,
	"term"	TEXT,
	"definition_id"	INTEGER,
	"definition"	TEXT,
	"quiz_answer"	INTEGER,
	"user_answer"	INTEGER,
	"result"	INTEGER,
	"answer_speed"	INTEGER
);
DROP TABLE IF EXISTS "QUIZ";
CREATE TABLE IF NOT EXISTS "QUIZ" (
	"_id"	INTEGER PRIMARY KEY AUTOINCREMENT,
	"cid"	TEXT,
	"sid"	TEXT,
	"did"	TEXT,
	"total_questions"	INTEGER,
	"correct_answers"	INTEGER,
	"result"	TEXT DEFAULT '100%',
	"created_on"	TEXT
);
DROP TABLE IF EXISTS "FLASHCARDS";
CREATE TABLE IF NOT EXISTS "FLASHCARDS" (
	"_id"	INTEGER PRIMARY KEY AUTOINCREMENT,
	"class_name"	TEXT,
	"section_name"	TEXT,
	"deckset_name"	TEXT,
	"term"	TEXT,
	"definition"	TEXT,
	"importance"	INTEGER,
	"hardness"	INTEGER,
	"review_hits"	INTEGER DEFAULT 0,
	"quiz_hits"	INTEGER DEFAULT 0,
	"created_on"	TEXT,
	"updated_on"	TEXT,
	"last_review"	TEXT,
	"last_quiz"	TEXT
);
DROP TABLE IF EXISTS "DECKSETS";
CREATE TABLE IF NOT EXISTS "DECKSETS" (
	"_id"	INTEGER,
	"deckset_name"	TEXT,
	"section_name"	TEXT,
	"class_name"	TEXT,
	"created_on"	TEXT,
	"updated_on"	TEXT,
	PRIMARY KEY("deckset_name","section_name","class_name")
);
DROP TABLE IF EXISTS "SECTIONS";
CREATE TABLE IF NOT EXISTS "SECTIONS" (
	"_id"	INTEGER,
	"section_name"	TEXT,
	"class_name"	TEXT,
	"created_on"	TEXT,
	"updated_on"	TEXT,
	PRIMARY KEY("section_name","class_name")
);
DROP TABLE IF EXISTS "CLASSES";
CREATE TABLE IF NOT EXISTS "CLASSES" (
	"_id"	INTEGER PRIMARY KEY AUTOINCREMENT,
	"name"	TEXT UNIQUE,
	"created_on"	TEXT,
	"updated_on"	TEXT
);
DROP TABLE IF EXISTS "android_metadata";
CREATE TABLE IF NOT EXISTS "android_metadata" (
	"locale"	TEXT DEFAULT 'en_US'
);
INSERT INTO "QUIZ_PROCESS" ("_id","quiz_id","deckset_name","section_name","class_name","term_id","term","definition_id","definition","quiz_answer","user_answer","result","answer_speed") VALUES (1,1,NULL,NULL,NULL,1,'C',NULL,NULL,NULL,NULL,NULL,NULL),
 (2,1,NULL,NULL,NULL,2,'E',NULL,NULL,NULL,NULL,NULL,NULL),
 (3,1,NULL,NULL,NULL,3,'D',NULL,NULL,NULL,NULL,NULL,NULL),
 (4,1,NULL,NULL,NULL,4,'B',NULL,NULL,NULL,NULL,NULL,NULL),
 (5,1,NULL,NULL,NULL,5,'D',NULL,NULL,NULL,NULL,NULL,NULL),
 (6,1,NULL,NULL,NULL,6,'B',NULL,NULL,NULL,NULL,NULL,NULL),
 (7,1,NULL,NULL,NULL,7,'B',NULL,NULL,NULL,NULL,NULL,NULL),
 (8,1,NULL,NULL,NULL,8,'C',NULL,NULL,NULL,NULL,NULL,NULL),
 (9,1,NULL,NULL,NULL,9,'D',NULL,NULL,NULL,NULL,NULL,NULL),
 (10,1,NULL,NULL,NULL,10,'E',NULL,NULL,NULL,NULL,NULL,NULL),
 (11,1,NULL,NULL,NULL,11,'C',NULL,NULL,NULL,NULL,NULL,NULL),
 (12,1,NULL,NULL,NULL,12,'B',NULL,NULL,NULL,NULL,NULL,NULL),
 (13,1,NULL,NULL,NULL,13,'C',NULL,NULL,NULL,NULL,NULL,NULL),
 (14,1,NULL,NULL,NULL,14,'E',NULL,NULL,NULL,NULL,NULL,NULL),
 (15,1,NULL,NULL,NULL,15,'E',NULL,NULL,NULL,NULL,NULL,NULL),
 (16,1,NULL,NULL,NULL,16,'C',NULL,NULL,NULL,NULL,NULL,NULL),
 (17,1,NULL,NULL,NULL,17,'C',NULL,NULL,NULL,NULL,NULL,NULL),
 (18,1,NULL,NULL,NULL,18,'E',NULL,NULL,NULL,NULL,NULL,NULL),
 (19,1,NULL,NULL,NULL,19,'E',NULL,NULL,NULL,NULL,NULL,NULL),
 (20,1,NULL,NULL,NULL,20,'E',NULL,NULL,NULL,NULL,NULL,NULL),
 (21,1,NULL,NULL,NULL,1,'C',NULL,NULL,NULL,NULL,NULL,NULL),
 (22,1,NULL,NULL,NULL,2,'E',NULL,NULL,NULL,NULL,NULL,NULL),
 (23,1,NULL,NULL,NULL,3,'D',NULL,NULL,NULL,NULL,NULL,NULL),
 (24,1,NULL,NULL,NULL,4,'B',NULL,NULL,NULL,NULL,NULL,NULL),
 (25,1,NULL,NULL,NULL,5,'D',NULL,NULL,NULL,NULL,NULL,NULL),
 (26,1,NULL,NULL,NULL,6,'B',NULL,NULL,NULL,NULL,NULL,NULL),
 (27,1,NULL,NULL,NULL,7,'B',NULL,NULL,NULL,NULL,NULL,NULL),
 (28,1,NULL,NULL,NULL,8,'C',NULL,NULL,NULL,NULL,NULL,NULL),
 (29,1,NULL,NULL,NULL,9,'D',NULL,NULL,NULL,NULL,NULL,NULL),
 (30,1,NULL,NULL,NULL,10,'E',NULL,NULL,NULL,NULL,NULL,NULL),
 (31,1,NULL,NULL,NULL,11,'C',NULL,NULL,NULL,NULL,NULL,NULL),
 (32,1,NULL,NULL,NULL,12,'B',NULL,NULL,NULL,NULL,NULL,NULL),
 (33,1,NULL,NULL,NULL,13,'C',NULL,NULL,NULL,NULL,NULL,NULL),
 (34,1,NULL,NULL,NULL,14,'E',NULL,NULL,NULL,NULL,NULL,NULL),
 (35,1,NULL,NULL,NULL,15,'E',NULL,NULL,NULL,NULL,NULL,NULL),
 (36,1,NULL,NULL,NULL,16,'C',NULL,NULL,NULL,NULL,NULL,NULL),
 (37,1,NULL,NULL,NULL,17,'C',NULL,NULL,NULL,NULL,NULL,NULL),
 (38,1,NULL,NULL,NULL,18,'E',NULL,NULL,NULL,NULL,NULL,NULL),
 (39,1,NULL,NULL,NULL,19,'E',NULL,NULL,NULL,NULL,NULL,NULL),
 (40,1,NULL,NULL,NULL,20,'E',NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO "FLASHCARDS" ("_id","class_name","section_name","deckset_name","term","definition","importance","hardness","review_hits","quiz_hits","created_on","updated_on","last_review","last_quiz") VALUES (1,'1','1','1','C','C',1,NULL,0,0,NULL,NULL,NULL,NULL),
 (2,'1','1','1','E','E',2,0,0,NULL,NULL,NULL,NULL,NULL),
 (3,'1','1','1','D','D',3,0,0,NULL,NULL,NULL,NULL,NULL),
 (4,'1','1','1','B','B',4,NULL,0,0,NULL,NULL,NULL,NULL),
 (5,'1','1','1','D','D',2,NULL,0,0,NULL,NULL,NULL,NULL),
 (6,'1','1','1','B','B',3,NULL,0,0,NULL,NULL,NULL,NULL),
 (7,'1','1','1','B','B',5,NULL,0,0,NULL,NULL,NULL,NULL),
 (8,'1','1','1','C','C',6,NULL,0,0,NULL,NULL,NULL,NULL),
 (9,'1','1','1','D','D',9,NULL,0,0,NULL,NULL,NULL,NULL),
 (10,'1','1','1','E','E',8,NULL,0,0,NULL,NULL,NULL,NULL),
 (11,'1','1','1','C','C',5,NULL,0,0,NULL,NULL,NULL,NULL),
 (12,'1','1','1','B','B',2,NULL,0,0,NULL,NULL,NULL,NULL),
 (13,'1','1','1','C','C',4,NULL,0,0,NULL,NULL,NULL,NULL),
 (14,'1','1','1','E','E',5,NULL,0,0,NULL,NULL,NULL,NULL),
 (15,'1','1','1','E','E',1,NULL,0,0,NULL,NULL,NULL,NULL),
 (16,'1','1','1','C','C',2,NULL,0,0,NULL,NULL,NULL,NULL),
 (17,'1','1','1','C','C',3,NULL,0,0,NULL,NULL,NULL,NULL),
 (18,'1','1','1','E','E',4,NULL,0,0,NULL,NULL,NULL,NULL),
 (19,'1','1','1','E','E',2,NULL,0,0,NULL,NULL,NULL,NULL),
 (20,'1','1','1','E','E',3,NULL,0,0,NULL,NULL,NULL,NULL),
 (21,'1','1','1','D','D',5,NULL,0,0,NULL,NULL,NULL,NULL),
 (22,'1','1','1','E','E',6,NULL,0,0,NULL,NULL,NULL,NULL),
 (23,'1','1','1','B','B',9,NULL,0,0,NULL,NULL,NULL,NULL),
 (24,'1','1','1','D','D',8,NULL,0,0,NULL,NULL,NULL,NULL),
 (25,'1','1','1','B','B',5,NULL,0,0,NULL,NULL,NULL,NULL),
 (26,'1','1','1','D','D',2,NULL,0,0,NULL,NULL,NULL,NULL),
 (27,'1','1','1','D','D',4,NULL,0,0,NULL,NULL,NULL,NULL),
 (28,'1','1','1','C','C',5,NULL,0,0,NULL,NULL,NULL,NULL),
 (29,'1','1','1','X','X',1,NULL,0,0,NULL,NULL,NULL,NULL),
 (30,'1','1','1','B','B',2,NULL,0,0,NULL,NULL,NULL,NULL),
 (31,'1','1','1','D','D',3,NULL,0,0,NULL,NULL,NULL,NULL),
 (32,'1','1','1','B','B',4,NULL,0,0,NULL,NULL,NULL,NULL),
 (33,'1','1','1','C','C',2,NULL,0,0,NULL,NULL,NULL,NULL),
 (34,'1','1','1','B','B',3,NULL,0,0,NULL,NULL,NULL,NULL),
 (35,'1','1','1','E','E',5,NULL,0,0,NULL,NULL,NULL,NULL),
 (36,'1','1','1','D','D',6,NULL,0,0,NULL,NULL,NULL,NULL),
 (37,'1','1','1','C','C',9,NULL,0,0,NULL,NULL,NULL,NULL),
 (38,'1','1','1','B','B',8,NULL,0,0,NULL,NULL,NULL,NULL),
 (39,'1','1','1','D','D',5,NULL,0,0,NULL,NULL,NULL,NULL),
 (40,'1','1','1','E','E',2,NULL,0,0,NULL,NULL,NULL,NULL),
 (41,'1','1','1','C','C',4,NULL,0,0,NULL,NULL,NULL,NULL),
 (42,'1','1','1','B','B',5,NULL,0,0,NULL,NULL,NULL,NULL),
 (43,'1','1','1','C','C',5,NULL,0,0,NULL,NULL,NULL,NULL),
 (44,'1','1','1','D','D',2,NULL,0,0,NULL,NULL,NULL,NULL),
 (45,'1','1','1','E','E',4,NULL,0,0,NULL,NULL,NULL,NULL),
 (46,'1','1','1','E','E',5,NULL,0,0,NULL,NULL,NULL,NULL),
 (47,'1','1','1','Z','Z',1,NULL,0,0,NULL,NULL,NULL,NULL),
 (48,'1','1','1','B','B',2,NULL,0,0,NULL,NULL,NULL,NULL),
 (49,'1','1','1','C','C',3,NULL,0,0,NULL,NULL,NULL,NULL),
 (50,'1','1','1','D','D',5,NULL,0,0,NULL,NULL,NULL,NULL);
INSERT INTO "DECKSETS" ("_id","deckset_name","section_name","class_name","created_on","updated_on") VALUES (1,'1','1','1','',NULL);
INSERT INTO "SECTIONS" ("_id","section_name","class_name","created_on","updated_on") VALUES (1,'1','1','','');
INSERT INTO "CLASSES" ("_id","name","created_on","updated_on") VALUES (1,'1','','');
COMMIT;
